- name: this is the example to gather the facts
  hosts: centos:ubuntu #all
  become: yes
  tasks:
  - name: tasks for gathering the facts
    ansible.builtin.debug:
      msg: "printing the facts: {{ansible_facts}}"

  - name: creating the user in centos
    ansible.builtin.command: useradd saikiran
    when: ansible_facts['distribution'] == "centos"

  - name: creating the user in ubuntu
    ansible.builtin.command: adduser saikiran
    when: ansible_facts['distribution'] == "ubuntu"