- name: This is configuring the catalogue service
  hosts: catalogue
  become: yes
  tasks:
  - name: installing the nodejs repos
    tags:
    - installation
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  
  - name: installing the nodejs
    tags:
    - installation
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: checking the user
    tags:
    - installation
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true


  - name: Creating the user
    tags:
    - installation
    ansible.builtin.user:
      name: roboshop
      state: present    
    when: output.rc != 0
  
  - name: Check if the directory exists
    tags:
    - installation
    ansible.builtin.stat:
      path: /app
    register: dir_check
    ignore_errors: true


  - name: Create the directory
    tags:
    - installation
    ansible.builtin.file:
      path: /app
      state: directory
    when: dir_check.stat.exists == False

  - name: Download the catalogue files
    tags:
    - deployment
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: Unarchive a file that is already on the remote machine
    tags:
    - deployment
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: Installing npm dependencies
    tags:
    - installation
    community.general.npm:
      name: npm
      path: /app
  
  - name: copying the catalogue.service
    tags:
    - installation
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/catalogue.service
      dest: /etc/systemd/system/catalogue.service

  
  - name: daemon reload catalogue
    tags:
    - installation
    ansible.builtin.systemd:
      daemon_reload: true
      name: catalogue

  - name: enabling the catalogue
    tags:
    - deployment
    ansible.builtin.service:
      name: catalogue
      enabled: yes
      state: restarted

  - name: setting up the mongodb repo file
    tags:
    - installation
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing the mongodbshell
    tags:
    - installation
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading the schema
    tags:
    - installation
    ansible.builtin.command: mongo --host mongodb.saikiransudhireddy.com < /app/schema/catalogue.js
     

  
