- name: this is the example to install nginx in multiple servers using the parallelsim
  hosts: nginx
  become: yes
  tasks:
  - name: Installing the Nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: enabling the nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes